### ISSUE TITLE
Deleting in a note in my.fleetingnotes.app should delete the note in Obsidian?

### ISSUE THREAD

**Issue by spiritualgeek** [fleetingnotes/fleeting-notes-obsidian#73] opened 2023-03-06 11:23 UTC
**Describe the bug**
When using the `One-way sync (FN =› Obsidian)` functionality in the plugin, I would expect that a note deleted through `my.fleetingnotes.app` would be deleted in Obsidian?

**To Reproduce**
Steps to reproduce the behaviour:
1. Delete a note in `my.fleetingnotes.app`
2. Re-synch 

**Expected behavior**
Note should be deleted from Obsidian?

**Screenshots**
N/A

**Device Info (please complete the following information):**
V0.5.5 of the plugin

**Additional context**
This also calls into question the model of the other sync options

- One-way sync (FN = Obsidian) + Delete from FN
- Real-time Two-way sync (FN # Obsidian)

Maybe there needs to be better description of behaviour?

**Comment by matthewwong525** [comment] 2023-03-06 15:59
Good point! Originally I was overly scared of unintentionally deleting notes but this does seem to be an expected behaviour. Thanks for putting in the bug report

**Comment by spiritualgeek** [comment] 2023-03-06 16:38
I did not know whether it was a bug or intentional. Thanks :)

**Comment by spiritualgeek** [comment] 2023-09-03 10:42
Not using fleeting notes anymore

**Comment by matthewwong525** [comment] 2023-09-10 23:25
Duplicate of #121

**Closed by matthewwong525** 2023-09-10 23:25 UTC
Labels: bug
